id: PB82823D0
initial_creation_type: input
source_metadata:
  title: Striking the Vital Point in Three Statements
  language: fr
  description: 'A series of texts based on the final testament of Garab Dorje, a key
    Dzogchen instruction known as ''Striking the Vital Point in Three Statements''
    (tshig gsum gnad brdegs):'
  volume:
    b3b7a120f353484592bc0d517fcb031c:
      title: Pith Instruction on the Three Crucial Statements
      parent: Advice
    ccbf01ba9aea48d3899290eb8947993f:
      title: The Three Statements that Strike the Vital Point
      parent: Root Text
    0499334df38947578ea8cd2d77741122:
      title: Summary of Striking the Vital Point in Three Statements
      parent: Summary
    ddcc6ca617754da58d7fca199864591f:
      title: The Special Teaching of the Wise and Glorious King – Commentary
      parent: Special Teaching of the Wise and Glorious King
    400ad46fe754443499e21f3019a94290:
      title: The Special Teaching of the Wise and Glorious King—Root Text
      parent: Special Teaching of the Wise and Glorious King
    4b2d71d904154ecb9f0d2209a4313d03:
      title: The Special Teaching of the Wise and Glorious King—Root Text (arranged
        in Tibetan-English verses)
      parent: Special Teaching of the Wise and Glorious King
    948494bba3cc4ced9a665820edf61532:
      title: Annotation Commentary on the Special Teaching of the Wise and Glorious
        King
      parent: Special Teaching of the Wise and Glorious King
created_at: '2022-03-01T05:58:24.343495'
last_modified_at: '2022-03-01T05:58:24.343498'
